cacheDuration: 60000000000
dbName: hatchet
host: 127.0.0.1
logger:
  format: console
  level: warn
maxConns: 50
maxQueueConns: 50
minConns: 10
minQueueConns: 10
password: hatchet
port: 5431
seed:
  adminEmail: david@contractsmarts.ai
  adminName: admin
  adminPassword: jbKZvonTxtL0yxahPh3BAg
  defaultTenantId: 707d0855-80ab-4e1f-a156-f1c4546cbf52
  defaultTenantName: Default
  defaultTenantSlug: default
sslMode: disable
username: hatchet
