additionalLoggers:
  pgxStats:
    format: console
    level: warn
  queue:
    format: console
    level: warn
alerting:
  sentry:
    environment: development
    sampleRate: 1
analytics:
  posthog: {}
auth:
  basicAuthEnabled: true
  cookie:
    domain: localhost
    insecure: true
    name: hatchet
    secrets: YJBMk9QtCMASPOQh JzdOXk3eln5RcYDp
  github:
    scopes:
    - read:user
    - user:email
  google:
    scopes:
    - openid
    - profile
    - email
email:
  postmark:
    fromName: Hatchet Support
enableDataRetention: true
encryption:
  cloudKms: {}
  jwt:
    privateJWTKeyset: eyJlbmNyeXB0ZWRLZXlzZXQiOiJBZkRtTnRWeFpIUlFMZlhvQ21xMWFJS0llbXdtWGJiNlJpYTV4Y2lkdFBoeU1Zb29KL0VWdURnbld5V0dGRkt5cXRDbWh5QTNKZXk3SEliUGJ5dElRUEFiOUJhREh2KzN5eXJ1SmhNZVp5bTM3cnc3ZUJzaWJVQWozZC9FMy9QVnE1c1ZxN1ZZamlKMm04bEpSeVl4Q1JiaEFKRmZZMDB2MG1PMk5PcHlMbHUwR3JUQmFVL2Rjb0JiNGkrb2lVcDRFUFVjbWhrK1hLeWNUZzVMRml0cFZ6SFBBbXVGemtkRjlZa25pT0Z0djNBMUg4UFV0SHRpd2dBWXBvcWh0aXVaWDVsZDVNQ1JvYUJjVlFiVE1COEp3Z2FUVzI2Q2lML3BaNWtZVjU4bCIsImtleXNldEluZm8iOnsicHJpbWFyeUtleUlkIjoxMDkwNDc3MTQsImtleUluZm8iOlt7InR5cGVVcmwiOiJ0eXBlLmdvb2dsZWFwaXMuY29tL2dvb2dsZS5jcnlwdG8udGluay5Kd3RFY2RzYVByaXZhdGVLZXkiLCJzdGF0dXMiOiJFTkFCTEVEIiwia2V5SWQiOjEwOTA0NzcxNCwib3V0cHV0UHJlZml4VHlwZSI6IlRJTksifV19fQ
    publicJWTKeyset: eyJlbmNyeXB0ZWRLZXlzZXQiOiJBZkRtTnRVR1VMbnU0RG9qN0h0djNkeWhyZ05zM0VHR3NydHQzYzBUWHcxU1ZDVytPc1JXZmtQQjN6dmN2aWhzSHJJOWU3WTlzMmZrcFZRc0ZUMFdyQmlOTldxVWhTNjFXdGRUU1l4S2NFR0FuSmhaelJDWnhmTkxxL0FEVS9iTjJheUcrU0FnejZxM2hlMzhyRUNya200TFdTWC94YTRnam1MWG5tMXpvSXArQWJkRlFPNVBjaGF6Zk0yeUNOTXJEbmE2QkpGUnZxL3RZQ3JITmVYYWY0a0JmVWMwRWhsTnlkdk83OTlTU1d0c21uYmdQb1ZndWNNPSIsImtleXNldEluZm8iOnsicHJpbWFyeUtleUlkIjoxMDkwNDc3MTQsImtleUluZm8iOlt7InR5cGVVcmwiOiJ0eXBlLmdvb2dsZWFwaXMuY29tL2dvb2dsZS5jcnlwdG8udGluay5Kd3RFY2RzYVB1YmxpY0tleSIsInN0YXR1cyI6IkVOQUJMRUQiLCJrZXlJZCI6MTA5MDQ3NzE0LCJvdXRwdXRQcmVmaXhUeXBlIjoiVElOSyJ9XX19
  masterKeyset: eyJwcmltYXJ5S2V5SWQiOjQwNDE2MTkxNTcsImtleSI6W3sia2V5RGF0YSI6eyJ0eXBlVXJsIjoidHlwZS5nb29nbGVhcGlzLmNvbS9nb29nbGUuY3J5cHRvLnRpbmsuQWVzR2NtS2V5IiwidmFsdWUiOiJHaUN1eUVudW43Q29KWUlBdUd2UTJSVkRHRitLSjdSb0FoWnpWVkY4ZFZSc0tBPT0iLCJrZXlNYXRlcmlhbFR5cGUiOiJTWU1NRVRSSUMifSwic3RhdHVzIjoiRU5BQkxFRCIsImtleUlkIjo0MDQxNjE5MTU3LCJvdXRwdXRQcmVmaXhUeXBlIjoiVElOSyJ9XX0
logger:
  format: console
  level: warn
monitoring:
  enabled: true
  permittedTenants: null
  probeTimeout: 30000000000
msgQueue:
  enabled: true
  kind: rabbitmq
  postgres:
    qos: 100
  rabbitmq:
    qos: 100
    url: amqp://hatchet_queue_user:rNjsBq49RGWLf0mlWGPslQ@hatchet-rabbitmq:5672/
otel:
  serviceName: server
  traceIdRatio: "1"
pylon: {}
runtime:
  allowChangePassword: true
  allowCreateTenant: true
  allowInvites: true
  allowSignup: true
  bufferCreateWorkflowRuns: true
  eventBuffer:
    flushItemsThreshold: 100
    flushPeriodMilliseconds: 10
    flushStrategy: DYNAMIC
    maxConcurrent: 50
    waitForFlush: 1000000
  flushItemsThreshold: 100
  flushPeriodMilliseconds: 10
  flushStrategy: DYNAMIC
  grpcBindAddress: 0.0.0.0
  grpcBroadcastAddress: hatchet-engine:7077
  grpcMaxMsgSize: 4194304
  grpcPort: 7077
  grpcRateLimit: 1000
  healthcheck: true
  limits:
    defaultCronAlarmLimit: 2
    defaultCronLimit: 5
    defaultEventAlarmLimit: 750
    defaultEventLimit: 1000
    defaultEventWindow: 86400000000000
    defaultScheduleAlarmLimit: 750
    defaultScheduleLimit: 1000
    defaultTenantRetentionPeriod: 720h
    defaultWorkerAlarmLimit: 2
    defaultWorkerLimit: 4
    defaultWorkflowRunAlarmLimit: 750
    defaultWorkflowRunLimit: 1000
    defaultWorkflowRunWindow: 86400000000000
  maxConcurrent: 50
  maxInternalRetryCount: 3
  maxPendingInvites: 100
  monitoring:
    enabled: true
    permittedTenants: null
    probeTimeout: 30000000000
  port: 8080
  queueStepRunBuffer:
    flushItemsThreshold: 100
    flushPeriodMilliseconds: 10
    flushStrategy: DYNAMIC
    maxConcurrent: 50
    waitForFlush: 1000000
  releaseSemaphoreBuffer:
    flushItemsThreshold: 100
    flushPeriodMilliseconds: 10
    flushStrategy: DYNAMIC
    maxConcurrent: 50
    waitForFlush: 1000000
  requeueLimit: 100
  shutdownWait: 20000000000
  singleQueueLimit: 100
  updateConcurrentFactor: 10
  updateHashFactor: 100
  url: http://localhost:8080
  waitForFlush: 1
  workflowRunBuffer:
    flushItemsThreshold: 100
    flushPeriodMilliseconds: 10
    flushStrategy: DYNAMIC
    maxConcurrent: 50
    waitForFlush: 1000000
securityCheck:
  enabled: true
  endpoint: https://security.hatchet.run
services:
- all
tenantAlerting:
  slack:
    scopes:
    - incoming-webhook
