cacheDuration: 60000000000
dbName: hatchet
host: hatchet-postgres
logger:
  format: console
  level: warn
maxConns: 50
maxQueueConns: 50
minConns: 10
minQueueConns: 10
password: tAaFn66DOCdO4WYS417qSw
port: 5432
seed:
  adminEmail: david@contractsmarts.ai
  adminName: admin
  adminPassword: t4HvbIETwW2xaLKMuk0rlg
  defaultTenantId: 707d0855-80ab-4e1f-a156-f1c4546cbf52
  defaultTenantName: Default
  defaultTenantSlug: default
sslMode: disable
username: hatchet_user
